"""Build the freestanding RV32I ROM using an existing 1-bit DPCM samples.bin."""

import argparse
from pathlib import Path
import json
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--toolchain', default='C:/msys64/ucrt64/bin')
    parser.add_argument('--rate', type=int, default=32000)
    parser.add_argument('--samples-bin', type=Path, default=ROOT / 'samples.bin')
    args = parser.parse_args()

    # Use the existing pre-encoded 1-bit DPCM bank.
    bank = args.samples_bin.read_bytes()

    if not bank:
        raise ValueError(f'{args.samples_bin} is empty')

    if len(bank) > 2 * 1024 * 1024:
        raise ValueError('DPCM bank does not fit in the card RAM')

    # 1-bit DPCM = 8 decoded audio samples per byte.
    sample_count = len(bank) * 8

    entries = [{
        'mode': 0,
        'start': 0,
        'samples': sample_count,
        'rate': args.rate,
        'bytes': len(bank),
    }]

    # Regenerate metadata/header for the existing samples.bin.
    (ROOT / 'samples.json').write_text(
        json.dumps(entries, indent=2) + '\n',
        encoding='utf-8'
    )

    table = (
        '/* Generated by build_demo.py */\n'
        'static const unsigned samples[][4] = {\n'
    )
    table += ''.join(
        '    {%d, %d, %d, %d},\n'
        % (e['mode'], e['start'], e['samples'], e['rate'])
        for e in entries
    )
    (ROOT / 'samples.h').write_text(
        table + '};\n',
        encoding='utf-8'
    )

    compiler = str(Path(args.toolchain) / 'riscv64-unknown-elf-gcc')
    objcopy = str(Path(args.toolchain) / 'riscv64-unknown-elf-objcopy')

    with tempfile.TemporaryDirectory(prefix='dpcm-build-') as temporary:
        elf = str(Path(temporary) / 'demo.elf')

        subprocess.run([
            compiler,
            '-march=rv32imf',
            '-mabi=ilp32',
            '-Os',
            '-ffreestanding',
            '-fno-builtin',
            '-nostdlib',
            '-mno-relax',
            '-msmall-data-limit=0',
            '-Wl,--build-id=none',
            '-T', str(ROOT / 'linker.ld'),
            str(ROOT / 'start.S'),
            str(ROOT / 'demo.c'),
            '-o', elf,
        ], check=True)

        subprocess.run([
            objcopy,
            '-O', 'binary',
            elf,
            str(ROOT / 'demo.rom'),
        ], check=True)

    duration = sample_count / args.rate

    print(
        f'Using {len(bank)} byte 1-bit DPCM bank '
        f'({sample_count} samples, {duration:.2f}s) and built '
        f'{(ROOT / "demo.rom").stat().st_size} byte RV32I ROM'
    )


if __name__ == '__main__':
    main()