```python
"""Build the freestanding RV32I ROM using an existing samples.bin/sample.json bank."""

import argparse
import json
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--toolchain', default='C:/msys64/ucrt64/bin')
    parser.add_argument('--samples-bin', type=Path, default=ROOT / 'samples.bin')
    parser.add_argument('--samples-json', type=Path, default=ROOT / 'samples.json')
    args = parser.parse_args()

    # Use the existing pre-built sample bank.
    bank = args.samples_bin.read_bytes()

    if not bank:
        raise ValueError(f'{args.samples_bin} is empty')

    if len(bank) > 0x1F0000:
        raise ValueError('bank overlaps CPU-generated sample')

    # Load the metadata describing the formats already stored in samples.bin.
    entries = json.loads(args.samples_json.read_text(encoding='utf-8'))

    if not entries:
        raise ValueError(f'{args.samples_json} contains no sample entries')

    # Sanity-check the metadata against samples.bin.
    for entry in entries:
        required = ('mode', 'start', 'samples', 'rate', 'bytes')
        missing = [key for key in required if key not in entry]
        if missing:
            raise ValueError(
                f'entry is missing fields: {", ".join(missing)}'
            )

        start = entry['start']
        size = entry['bytes']

        if start < 0 or size < 0 or start + size > len(bank):
            raise ValueError(
                f'sample mode {entry["mode"]} lies outside samples.bin'
            )

    # Regenerate samples.h from the existing metadata.
    table = (
        '/* Generated by build_demo.py */\n'
        'static const unsigned samples[][4] = {\n'
    )

    table += ''.join(
        '    {%d, %d, %d, %d},\n'
        % (
            entry['mode'],
            entry['start'],
            entry['samples'],
            entry['rate'],
        )
        for entry in entries
    )

    (ROOT / 'samples.h').write_text(
        table + '};\n',
        encoding='utf-8'
    )

    compiler = str(Path(args.toolchain) / 'riscv64-unknown-elf-gcc')
    objcopy = str(Path(args.toolchain) / 'riscv64-unknown-elf-objcopy')

    with tempfile.TemporaryDirectory(prefix='adpcm-build-') as temporary:
        elf = str(Path(temporary) / 'demo.elf')

        subprocess.run([
            compiler,
            '-march=rv32i',
            '-mabi=ilp32',
            '-Os',
            '-ffreestanding',
            '-fno-builtin',
            '-nostdlib',
            '-mno-relax',
            '-msmall-data-limit=0',
            '-Wl,--build-id=none',
            '-T', str(ROOT / 'linker.ld'),
            str(ROOT / 'start.S'),
            str(ROOT / 'demo.c'),
            '-o', elf,
        ], check=True)

        subprocess.run([
            objcopy,
            '-O', 'binary',
            elf,
            str(ROOT / 'demo.rom'),
        ], check=True)

    print(
        f'Using existing {len(bank)} byte sample bank with '
        f'{len(entries)} sample formats and built '
        f'{(ROOT / "demo.rom").stat().st_size} byte RV32I ROM'
    )


if __name__ == '__main__':
    main()
```
