#include "samples.h"

static volatile unsigned char *const card = (volatile unsigned char *)0x10000000;
// Native demo test and the Memory panel can inspect these RAM words.
static volatile unsigned *const progress = (volatile unsigned *)0x10000;

static void word(unsigned offset, unsigned value) {
    for (unsigned byte = 0; byte != 4; ++byte) {
        card[offset + byte] = (unsigned char)value;
        value >>= 8;
    }
}

static void play(unsigned mode, unsigned start, unsigned length, unsigned rate, unsigned stage) {
    card[1] = 2;
    card[0] = (unsigned char)mode;
    word(4, start);
    word(8, length);
    word(12, rate);
    progress[0] = stage;
    card[1] = 1;
    while (card[1] & 1) {}
    if (card[1] & 128) {
        progress[3] = 0xBAD;
        for (;;) {}
    }
    progress[1] |= 1u << stage;
}

void main(void) {
    progress[0] = progress[1] = progress[2] = progress[3] = 0;
    card[2] = 192;
    // Generate a half-second triangle in the card's private RAM using only
    // address/data registers. No sample RAM appears in the CPU address space.
    word(16, 0x1F0000);
    for (unsigned i = 0; i < 8000; ++i) {
        unsigned phase = i & 63;
        int amplitude = phase < 32 ? (int)phase * 4 - 64 : 192 - (int)phase * 4;
        card[20] = (unsigned char)amplitude;
    }
    // Read back the first generated byte, then patch it and restore it.
    word(16, 0x1F0000);
    unsigned char first = card[20];
    word(16, 0x1F0000);
    card[20] = 0;
    word(16, 0x1F0000);
    if (card[20] != 0 || first != 192) {
        progress[3] = 0xBAD;
        for (;;) {}
    }
    word(16, 0x1F0000);
    card[20] = first;
    for (;;) {
        for (unsigned i = 0; i < 5; ++i)
            play(samples[i][0], samples[i][1], samples[i][2], samples[i][3], i);
        play(2, 0x1F0000, 8000, 16000, 5);
        ++progress[2];
    }
}
